user exception caught
error call caught
no method error
exceptionsrun001.hs:38:0-12: Non-exhaustive patterns in function test1
exceptionsrun001.hs:45:0-25: Non-exhaustive patterns in function test2
43