
T4174.hs:42:12:
    Couldn't match type `False' with `True'
    In the expression: sync_large_objects
    In an equation for `testcase': testcase = sync_large_objects
